# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThemeSwitcherDialog
                                 A QGIS plugin
 This plugin adds a popup to easily switch between layer themes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Roel Huybrechts
        email                : roel@huybrechts.re
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtWidgets, QtGui, QtCore


class ThemeButton(QtWidgets.QToolButton):
    def __init__(self, theme, themeConfig, dialog, parent=None):
        super().__init__(parent)
        self.theme = theme
        self.themeConfig = themeConfig
        self.dialog = dialog

        self.iconPath = ':/plugins/theme_switcher/map.png'
        self.setIcon(QtGui.QIcon(self.iconPath))
        self.setIconSize(QtCore.QSize(64, 64))

        self.setText(self.theme)
        self.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.clicked.connect(self.switchToTheme)

    def switchToTheme(self):
        self.themeConfig.mapThemeCollection.applyTheme(
            self.theme, self.themeConfig.layerTreeRoot, self.themeConfig.layerTreeModel)

        self.dialog.close()


class ThemeSwitcherDialog(QtWidgets.QDialog):
    def __init__(self, main):
        """Constructor."""
        QtWidgets.QDialog.__init__(self)
        self.main = main
        self.themeConfig = self.main.themeConfig

        self.iconPath = ':/plugins/theme_switcher/map.png'
        self.setWindowIcon(QtGui.QIcon(self.iconPath))

        self.setWindowTitle(self.main.tr(u'Theme switcher'))
        self.setLayout(QtWidgets.QHBoxLayout())

        self.populate()
        self.themeConfig.configChanged.connect(self.populate)

    def populate(self):
        # remove all buttons
        for i in reversed(range(self.layout().count())):
            self.layout().itemAt(i).widget().setParent(None)

        # add button for each theme
        for theme in self.themeConfig.themes:
            btn = ThemeButton(theme, self.themeConfig, self)
            self.layout().addWidget(btn)
